services:
    _defaults:
        autowire: true
        autoconfigure: true

    Hengebytes\ResponseFilterBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Entity/'
            - '../../Resources/'
            - '../../HBResponseFilterBundle.php'


