services:
    _defaults:
        autowire: true
        autoconfigure: true

    ResponseFilterBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Entity/'
            - '../../Resources/'
            - '../../ResponseFilterBundle.php'


